import { FaLocationDot, FaHouseUser, FaStar, FaExpand, FaBed, FaShower } from 'react-icons/fa6';
import Image1 from './ImagesData/last-about-image1.jpg';
import Image2 from './ImagesData/last-about-image2.jpg';
import Image3 from './ImagesData/last-about-image3.jpg';
import Image4 from './ImagesData/last-about-image4.jpg';
import Image5 from './ImagesData/last-about-image5.jpg';
import Image6 from './ImagesData/last-about-image6.jpg';
import Authoruser from './ImagesData/author-image.jpg';

const data = [
    {
        img: Image1,
        autherimg: Authoruser,
        starraiting: FaStar,
        raitingnumerical: `5.0`,
        raitingnumericaluser: `(1)`,
        heading: `Nova Quincy Apartment`,
        locationsymboll: FaLocationDot,
        locationaddress: `18 Broklyn Street, New York`,
        paragraph: `It is a long established fact that a reader will be distracted the readable content.`,
        icononeimg: FaExpand,
        iconone: `1860 sqft`,
        icontwoimg: FaBed,
        icontwo: `Bed 6`,
        iconthreeimg: FaShower,
        iconthree: `Bath 6`,
        bottomprice: `$1800`,
        bottombtnicon: FaHouseUser,
        bottombtn: `Details`,
    },
    {
        img: Image2,
        autherimg: Authoruser,
        starraiting: FaStar,
        raitingnumerical: `5.0`,
        raitingnumericaluser: `(1)`,
        heading: `West Squaer Apartments`,
        locationsymboll: FaLocationDot,
        locationaddress: `18 Broklyn Street, New York`,
        paragraph: `It is a long established fact that a reader will be distracted the readable content.`,
        icononeimg: FaExpand,
        iconone: `1860 sqft`,
        icontwoimg: FaBed,
        icontwo: `Bed 6`,
        iconthreeimg: FaShower,
        iconthree: `Bath 6`,
        bottomprice: `$1800`,
        bottombtnicon: FaHouseUser,
        bottombtn: `Details`,
    },
    {
        img: Image3,
        autherimg: Authoruser,
        starraiting: FaStar,
        raitingnumerical: `4.0`,
        raitingnumericaluser: `(1)`,
        heading: `Peninsula Apartments`,
        locationsymboll: FaLocationDot,
        locationaddress: `18 Broklyn Street, New York`,
        paragraph: `It is a long established fact that a reader will be distracted the readable content.`,
        icononeimg: FaExpand,
        iconone: `1860 sqft`,
        icontwoimg: FaBed,
        icontwo: `Bed 6`,
        iconthreeimg: FaShower,
        iconthree: `Bath 6`,
        bottomprice: `$1800`,
        bottombtnicon: FaHouseUser,
        bottombtn: `Details`,
    },
    {
        img: Image4,
        autherimg: Authoruser,
        starraiting: FaStar,
        raitingnumerical: `5.0`,
        raitingnumericaluser: `(1)`,
        heading: `West Squaer Apartments`,
        locationsymboll: FaLocationDot,
        locationaddress: `18 Broklyn Street, New York`,
        paragraph: `It is a long established fact that a reader will be distracted the readable content.`,
        icononeimg: FaExpand,
        iconone: `1860 sqft`,
        icontwoimg: FaBed,
        icontwo: `Bed 6`,
        iconthreeimg: FaShower,
        iconthree: `Bath 6`,
        bottomprice: `$1800`,
        bottombtnicon: FaHouseUser,
        bottombtn: `Details`,
    },
    {
        img: Image5,
        autherimg: Authoruser,
        starraiting: FaStar,
        raitingnumerical: `5.0`,
        raitingnumericaluser: `(1)`,
        heading: `West Squaer Apartments`,
        locationsymboll: FaLocationDot,
        locationaddress: `18 Broklyn Street, New York`,
        paragraph: `It is a long established fact that a reader will be distracted the readable content.`,
        icononeimg: FaExpand,
        iconone: `1860 sqft`,
        icontwoimg: FaBed,
        icontwo: `Bed 6`,
        iconthreeimg: FaShower,
        iconthree: `Bath 6`,
        bottomprice: `$1800`,
        bottombtnicon: FaHouseUser,
        bottombtn: `Details`,
    },
    {
        img: Image6,
        autherimg: Authoruser,
        starraiting: FaStar,
        raitingnumerical: `5.0`,
        raitingnumericaluser: `(1)`,
        heading: `Nova Quincy Apartment`,
        locationsymboll: FaLocationDot,
        locationaddress: `18 Broklyn Street, New York`,
        paragraph: `It is a long established fact that a reader will be distracted the readable content.`,
        icononeimg: FaExpand,
        iconone: `1860 sqft`,
        icontwoimg: FaBed,
        icontwo: `Bed 6`,
        iconthreeimg: FaShower,
        iconthree: `Bath 6`,
        bottomprice: `$1800`,
        bottombtnicon: FaHouseUser,
        bottombtn: `Details`,
    }  

];

export default data;